[tool.pytest.ini_options]
addopts = "-s --disable-pytest-warnings"
DJANGO_SETTINGS_MODULE = "the_spymaster.settings"

[tool.coverage.run]
source = ["api", "the_spymaster", "telegram_bot"]

[tool.black]
line-length = 120

[tool.isort]
skip = ["__init__.py"]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
