[default]
env_verbose_name = "Not set"

# Django
django_secret_key = "u04*+#&)cpg282xzxjd6if167%twq_&^8+ty_7xtz#b5)&_d09"
django_debug = false

# Logging
indented_json = 0
formatter = "json"
root_log_level = "INFO"
bot_log_level = "INFO"

# App
base_backend_url = "http://127.0.0.1:8000"

# Language
language_data_folder = "/tmp/language_data"
should_load_models_from_s3 = false
s3_bucket_name = "the-spymaster-bucket-dev"

[local]
env_verbose_name = "Local"
django_debug = true
formatter = "simple"
should_load_models_from_s3 = true
#language_data_folder = "~/.cache/language_data"
bot_log_level = "DEBUG"

[dev]
env_verbose_name = "Dev"
django_debug = true
db_name = "postgres"
db_engine = "django.db.backends.postgresql"
db_port = 5432
should_load_models_from_s3 = true

[stage]
env_verbose_name = "Staging"
db_name = "postgres"
db_engine = "django.db.backends.postgresql"
db_port = 5432
should_load_models_from_s3 = true

[prod]
env_verbose_name = "Production"
db_name = "postgres"
db_engine = "django.db.backends.postgresql"
db_port = 5432
should_load_models_from_s3 = true
s3_bucket_name = "the-spymaster-bucket-prod"

[rsbpi]
env_verbose_name = "Raspberry Pi"
base_backend_url = "http://192.168.1.240:8000"
