[default]
env_verbose_name = "Not set"

# Django
django_secret_key = "u04*+#&)cpg282xzxjd6if167%twq_&^8+ty_7xtz#b5)&_d09"
django_debug = false

# Logging
indent_json = false
std_formatter = "json"
root_log_level = "INFO"

# Language
language_data_folder = "/tmp/language_data"
should_load_models_from_s3 = false
s3_bucket_name = "the-spymaster-bucket-dev"

[local]
env_verbose_name = "Local"
django_debug = true
std_formatter = "simple"
should_load_models_from_s3 = true
#language_data_folder = "~/.cache/language_data"

[dev]
env_verbose_name = "Dev"
django_debug = true
db_engine = "django.db.backends.postgresql"
db_name = "postgres"
db_port = 5432
should_load_models_from_s3 = true

[stage]
env_verbose_name = "Staging"
django_debug = true
db_engine = "django.db.backends.postgresql"
db_name = "postgres"
db_port = 5432
should_load_models_from_s3 = true

[prod]
env_verbose_name = "Production"
should_load_models_from_s3 = true
db_engine = "django.db.backends.postgresql"
db_name = "postgres"
db_port = 5432
s3_bucket_name = "the-spymaster-bucket-prod"

[rsbpi]
env_verbose_name = "Raspberry Pi"
