name: Deploy
description: "A reusable action to deploy the application using Terraform."

inputs:
  # The name of the Terraform workspace to use
  workspace:
    description: "The name of the Terraform workspace to use"
    required: true
    default: "default"
  sha:
    description: "The commit SHA to deploy"
    required: true
  aws_access_key_id:
    description: "AWS access key ID"
    required: true
  aws_secret_access_key:
    description: "AWS secret access key"
    required: true
  aws_region:
    description: "The AWS region to deploy to"
    required: true
    default: "us-east-1"
  sentry_dsn:
    description: "Sentry DSN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set env vars
      shell: bash
      run: |
          echo "AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ inputs.aws_secret_access_key }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ inputs.aws_region }}" >> $GITHUB_ENV
          echo "TF_VAR_FILE=tf/${{ inputs.workspace }}.tfvars" >> $GITHUB_ENV
    - name: Create tfvars files
      shell: bash
      run: |
        echo "sentry_dsn = \"${{ inputs.sentry_dsn }}\"" > ${TF_VAR_FILE}
    - name: Download deploy artifact
      uses: actions/download-artifact@v4
      with:
        name: deployment-${{ inputs.sha }}
        path: ./.deployment
    - name: Install CI dependencies
      shell: bash
      run: make install-ci
    - name: Terraform init
      shell: bash
      run: cd tf; terraform init
    - name: Terraform plan
      shell: bash
      run: make plan WORKSPACE=${{ inputs.workspace }}
    - name: Terraform apply
      shell: bash
      run: make apply
