[default]
env_verbose_name = "Not set"
load_ssm_secrets = true

# Django
django_debug = false

# Logging
indent_json = false
std_formatter = "json"
root_log_level = "DEBUG"

# Solvers
solvers_backend_url = "http://localhost:5000"

[test]
env_verbose_name = "Test"
django_debug = true
std_formatter = "simple"
load_ssm_secrets = false

[local]
env_verbose_name = "Local"
django_debug = true
std_formatter = "simple"
load_ssm_secrets = false

[dev]
env_verbose_name = "Dev"
django_debug = true
solvers_backend_url = "https://solvers.dev.the-spymaster.xyz"

[stage]
env_verbose_name = "Staging"
django_debug = true

[prod]
env_verbose_name = "Production"
solvers_backend_url = "https://solvers.the-spymaster.xyz"

[rsbpi]
env_verbose_name = "Raspberry Pi"
