# Generated by Django 4.0.8 on 2022-12-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_state_json_game_state_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Game",
        ),
    ]
