[default]
env_verbose_name = "Not set"
load_ssm_secrets = true

# Django
django_secret_key = "u04*+#&)cpg282xzxjd6if167%twq_&^8+ty_7xtz#b5)&_d09"
django_debug = false

# Logging
indent_json = false
std_formatter = "json"
root_log_level = "INFO"

# Solvers
solvers_backend_url = "http://localhost:5000"

[test]
env_verbose_name = "Test"
django_debug = true
load_ssm_secrets = false

[local]
env_verbose_name = "Local"
django_debug = true
std_formatter = "simple"
load_ssm_secrets = false

[dev]
env_verbose_name = "Dev"
django_debug = true
db_engine = "django.db.backends.postgresql"
db_name = "postgres"
db_port = 5432
db_user = "spymaster_admin"
db_host = "the-spymaster-backend-dev-db.cb5zziruvvzx.us-east-1.rds.amazonaws.com"
solvers_backend_url = "https://solvers.dev.the-spymaster.xyz"

[stage]
env_verbose_name = "Staging"
django_debug = true
db_engine = "django.db.backends.postgresql"
db_name = "postgres"
db_port = 5432
db_user = "spymaster_admin"
db_host = "the-spymaster-db..eu-central-1.rds.amazonaws.com"

[prod]
env_verbose_name = "Production"
db_engine = "django.db.backends.postgresql"
db_name = "postgres"
db_port = 5432
db_user = "spymaster_admin"
db_host = "the-spymaster-db.cwerl06excux.eu-central-1.rds.amazonaws.com"
solvers_backend_url = "https://solvers.the-spymaster.xyz"

[rsbpi]
env_verbose_name = "Raspberry Pi"
